// Code generated by "stringer -type ContentEncoding -linecomment"; DO NOT EDIT.

package manifest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Identity-0]
	_ = x[Gzip-1]
	_ = x[Deflate-2]
}

const _Encoding_name = "identitygzipdeflate"

var _Encoding_index = [...]uint8{0, 8, 12, 19}

func (i ContentEncoding) String() string {
	if i < 0 || i >= ContentEncoding(len(_Encoding_index)-1) {
		return "ContentEncoding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Encoding_name[_Encoding_index[i]:_Encoding_index[i+1]]
}
