// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"context"
	"github.com/ajjensen13/gke"
	"github.com/spf13/cobra"
	"net/http"
)

// Injectors from wire.go:

func InjectServer(ctx context.Context, lg gke.Logger, cmd *cobra.Command) (*http.Server, error) {
	cmdWebRoot, err := provideWebRoot(cmd)
	if err != nil {
		return nil, err
	}
	cmdModeType, err := provideMode(cmd)
	if err != nil {
		return nil, err
	}
	site, err := provideSite(cmdWebRoot, cmdModeType, lg)
	if err != nil {
		return nil, err
	}
	handler := provideHandler(site, lg)
	cmdAddrType, err := provideAddr(cmd)
	if err != nil {
		return nil, err
	}
	server, err := provideServer(ctx, handler, lg, cmdAddrType)
	if err != nil {
		return nil, err
	}
	return server, nil
}
